Marooned/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('island/', admin.site.urls),
                  path('', include('island.urls')),
                  path('', include('users.urls')),
                  path('news/', include('news.urls')),
                  path('summernote/', include('django_summernote.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

news/urls.py
from django.urls import path
from .views import (NewsListView, NewsDetailView, NewsCreateView, NewsUpdateView, NewsDeleteView,
                    UserPostListView, TagListView, tag_detail)

app_name = 'news'
urlpatterns = [
    path('', NewsListView.as_view(), name='news'),
    path('author/<str:username>/', UserPostListView.as_view(), name='user-posts'),
    path('new/', NewsCreateView.as_view(), name='news-create'),
    path('tags/', TagListView.as_view(), name='tags'),
    path('tags/<slug:slug>/', tag_detail, name='tag-detail'),
    path('<slug:slug>/', NewsDetailView.as_view(), name='post'),
    path('<slug:slug>/update/', NewsUpdateView.as_view(), name='news-update'),
    path('<slug:slug>/delete/', NewsDeleteView.as_view(), name='news-delete'),
]

news/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
STATUS = (
    (0, "Draft"),
    (1, "Publish")
)


class Tag(models.Model):
    tag_name = models.CharField(max_length=64, unique=True)
    tag_slug = models.SlugField(max_length=64, unique=True)
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.tag_name

    def get_absolute_url(self):
        return reverse("news:tag-detail", kwargs={"slug": str(self.tag_slug)})


class News(models.Model):
    title = models.CharField(max_length=192, unique=True)
    slug = models.SlugField(max_length=192, unique=True)
    cover_photo = models.ImageField(upload_to='news', blank=True, null=True)
    summary = models.CharField(max_length=280)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=1)
    tags = models.ManyToManyField(Tag, blank=True, related_name='post_tag')

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("news:post", kwargs={"slug": str(self.slug)})

# class Comment(models.Model):
#     post = models.ForeignKey(News, on_delete=models.CASCADE, related_name='comments')
#     name = models.CharField(max_length=96)
#     email = models.EmailField()
#     body = models.TextField()
#     created_on = models.DateTimeField(auto_now_add=True)
#     active = models.BooleanField(default=False)
#
#     class Meta:
#         ordering = ['created_on']
#
#     def __str__(self):
#         return 'Comment {} by {}'.format(self.body, self.name)

news/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget
from .models import News


class NewsPublishForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['title', 'slug', 'cover_photo', 'summary', 'content', 'tags']
        widgets = {
            'content': SummernoteWidget(),
        }

news/views.py
from .models import News, Tag
from .forms import NewsPublishForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render


# Create your views here.
class NewsListView(ListView):
    queryset = News.objects.filter(status=1).order_by('-created_on')
    context_object_name = 'news_list'
    paginate_by = 5


class NewsDetailView(DetailView):
    model = News
    context_object_name = 'post'


class NewsCreateView(LoginRequiredMixin, CreateView):
    # model = News
    # fields = ['title', 'slug', 'cover_photo', 'summary', 'content', 'tags']

    # using form_class so i can use summernote
    form_class = NewsPublishForm
    template_name = 'news/news_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(NewsCreateView, self).form_valid(form)


class NewsUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = News

    form_class = NewsPublishForm
    template_name = 'news/news_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(NewsUpdateView, self).form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class NewsDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = News
    success_url = '/news/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class UserPostListView(ListView):
    model = News
    template_name = 'news/user_posts.html'
    context_object_name = 'news_list'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return News.objects.filter(author=user).order_by('-created_on')


class TagListView(ListView):
    queryset = Tag.objects.all()
    template_name = 'news/tags.html'
    context_object_name = 'tag_list'


def tag_detail(request, slug):
    tag = Tag.objects.get(tag_slug__iexact=slug)
    return render(request, 'news/tag_detail.html', context={'tag': tag})

templates/news/blog.html
{% extends "base.html" %}
{% block title %}
    News Feed {{ block.super }}
{% endblock %}

{% block body %}
    <style>
        body {
            font-family: "Roboto", sans-serif;
            font-size: 18px;
            background-color: #fdfdfd;
        }

        .head_text {
            color: white;
        }

        .card {
            box-shadow: 0 16px 48px #E3E7EB;
        }
    </style>

    <header class="masthead">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class=" col-md-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my awesome Blog </h3>
                        <p class="text-light">We Love Django As much as you do..! &nbsp
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-8 mt-3 left">
                {% for post in news_list %}
                    <div class="card mb-4">
                        <div class="card-body">
                            <img width="200" height="200" src="{{ post.cover_photo.url }}" alt="Cover Photo" class="rounded float-right">
                            <h2 class="card-title">{{ post.title }}</h2>
                            <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on }} </p>
                            <p class="card-text">{{ post.summary | slice:":200" }}</p>
                            <a href="{% url 'news:post' post.slug %}" class="btn btn-primary">Read More &rarr;</a>
                        </div>
                    </div>
                {% endfor %}

            </div>
            {% block sidebar %} {% include 'news/sidebar.html' %} {% endblock sidebar %}
        </div>
    </div>
    {% if is_paginated %}
        <nav aria-label="Page navigation conatiner"></nav>
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
        </nav>
        </div>
    {% endif %}
{% endblock %}

templates/news/news_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    Sign Up {{ block.super }}
{% endblock %}

{% block body %}
    <div class="container-fluid col-md-8">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete this post: {{ object.title }}</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete!</button>
                <a href="{% url 'news:post' object.slug %}" class="btn btn-outline-secondary">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

templates/news/news_detail.html
{% extends 'base.html' %}
{% block title %}
    {{ post.title }} {{ block.super }}
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 card mb-4  mt-4 left  top">
                <div class="card-body">
                    <h1 class="text-dark text-center">{{ post.title }}</h1>
                    <hr>
                    <h5 class="text-center">Summary: {{ post.summary }}</h5>
                    <hr>
                    <div class="row">
                        <a href="{% url 'news:user-posts' post.author.username %}"
                           class="h6 col-4 text-center">{{ post.author }}</a>
                        <p class="text-muted text-center col-4 h6">Published: {{ post.created_on }} </p>
                        {% if post.updated_on > post.created_on %}
                            <p class="text-muted text-center col-4 h6">Updated on: {{ post.updated_on }} </p>
                        {% endif %}
                    </div>
                    <hr>
                    {% if post.tags.all %}
                        <p class="text-muted text-center">Tags:
                            {% for tag in post.tags.all %}
                                <a href="{{ tag.get_absolute_url }}">
                                    <span class="badge badge-info">{{ tag.tag_name }}</span></a>
                            {% endfor %}</p>
                        <hr>
                    {% endif %}
                    {% if post.cover_photo %}
                        <img src="{{ post.cover_photo.url }}" class="img-fluid" alt="Responsive Cover image">
                        <hr>
                    {% endif %}
                    <p class="card-body embed-responsive">{{ post.content | safe }}</p>
                </div>
                <div class="simple">
                    {% if post.author == user %}
                        <a href="{% url 'news:news-update' post.slug %}" class="btn btn-outline-warning">Update</a>
                        <a href="{% url 'news:news-delete' post.slug %}" class="btn btn-outline-danger">Delete</a>
                    {% endif %}
                </div>

            </div>
            {% block sidebar %} {% include 'news/baby_template/sidebar.html' %} {% endblock sidebar %}
        </div>
    </div>

{% endblock %}

templates/news/news_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Write {{ block.super }}
{% endblock %}

{% block body %}
    <div class="container-fluid col-md-8">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Publish Your Blog</legend>
                {{ form | crispy | safe }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-success" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/news/news_list.html
{% extends "base.html" %}
{% block title %}
    News Feed {{ block.super }}
{% endblock %}

{% block body %}
    <style>
        body {
            font-family: "Roboto", sans-serif;
            font-size: 18px;
            background-color: #fdfdfd;
        }

        .head_text {
            color: white;
        }

        .card {
            box-shadow: 0 16px 48px #E3E7EB;
        }
    </style>
    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-8 mt-4 left">
                {% for post in news_list %}
                    {% include 'news/baby_template/news_card.html' %}
                {% endfor %}

            </div>
            {% block sidebar %} {% include 'news/baby_template/sidebar.html' %} {% endblock sidebar %}
        </div>
    </div>
    {% if is_paginated %}
        {#        <nav aria-label="Page navigation conatiner"></nav>#}
        <ul class="pagination justify-content-center m-auto">
            {% if page_obj.has_previous %}
                <a href="?page=1" class="btn btn-outline-info mb-4">First</a>
                <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-info mb-4 ml-1 mr-2">&laquo;
                    PREV</a>
            {% endif %}

            {% for page in page_obj.paginator.page_range %}
                {% if page_obj.number == page %}
                    <li><a href="?page={{ page }}" class="btn btn-info mb-4 mr-1">{{ page }}</a></li>
                {% elif page > page_obj.number|add:'-3' and page < page_obj.number|add:'3' %}
                    <li><a href="?page={{ page }}" class="btn btn-outline-info mb-4 mr-1">{{ page }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-info mb-4 ml-1 mr-1">NEXT
                    &raquo;</a></li>
                <li><a href="?page={{ page_obj.paginator.num_pages }}"
                       class="btn btn-outline-info mb-4">Last</a></li>
            {% endif %}
        </ul>
        </nav>
        </div>
    {% endif %}
{% endblock %}

templates/news/tag_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ tag.tag_name }} {{ block.super }}
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-8 mt-4 left">
                <h1 class="mb-4 text-center">post with <span
                        class="badge badge-info rounded"> {{ tag.tag_name }} </span> tag</h1>
                {% for post in tag.post_tag.all %}
                    {% include 'news/baby_template/news_card.html' %}
                {% endfor %}
            </div>
            {% block sidebar %} {% include 'news/baby_template/sidebar.html' %} {% endblock sidebar %}
        </div>
    </div>
{% endblock %}

templates/news/tags.html
{% extends 'base.html' %}
{% block title %}
    Tags {{ block.super }}
{% endblock %}
{% block body %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-8 mt-4 left">
                {% for tag in tag_list %}
                    <h5><a href="{{ tag.get_absolute_url }}">
                        <span class="badge badge-info">{{ tag }}</span></a></h5>
                {% endfor %}
            </div>
            {% block sidebar %} {% include 'news/baby_template/sidebar.html' %} {% endblock sidebar %}
        </div>
    </div>
{% endblock %}

templates/news/user_posts.html
{% extends "base.html" %}
{% block title %}
    {{ view.kwargs.username | capfirst }} Feed {{ block.super }}
{% endblock %}

{% block body %}
    <style>
        body {
            font-family: "Roboto", sans-serif;
            font-size: 18px;
            background-color: #fdfdfd;
        }

        .head_text {
            color: white;
        }

        .card {
            box-shadow: 0 16px 48px #E3E7EB;
        }
    </style>
    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-8 mt-4 left">
                <h2 class="text-center mb-4">Author: <span
                        class="badge badge-primary rounded-pill "> {{ view.kwargs.username }} </span> and author
                    have {{ page_obj.paginator.count }} posts</h2>
                {% for post in news_list %}
                    {% include 'news/baby_template/news_card.html' %}
                {% endfor %}

            </div>
            {% block sidebar %} {% include 'news/baby_template/sidebar.html' %} {% endblock sidebar %}
        </div>
    </div>
    {% if is_paginated %}
        {#        <nav aria-label="Page navigation conatiner"></nav>#}
        <ul class="pagination justify-content-center m-auto">
            {% if page_obj.has_previous %}
                <a href="?page=1" class="btn btn-outline-info mb-4">First</a>
                <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-info mb-4 ml-1 mr-2">&laquo;
                    PREV</a>
            {% endif %}

            {% for page in page_obj.paginator.page_range %}
                {% if page_obj.number == page %}
                    <li><a href="?page={{ page }}" class="btn btn-info mb-4 mr-1">{{ page }}</a></li>
                {% elif page > page_obj.number|add:'-3' and page < page_obj.number|add:'3' %}
                    <li><a href="?page={{ page }}" class="btn btn-outline-info mb-4 mr-1">{{ page }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-info mb-4 ml-1 mr-1">NEXT
                    &raquo;</a></li>
                <li><a href="?page={{ page_obj.paginator.num_pages }}"
                       class="btn btn-outline-info mb-4">Last</a></li>
            {% endif %}
        </ul>
        </nav>
        </div>
    {% endif %}
{% endblock %}