Marooned/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('island/', admin.site.urls),
                  path('', include('island.urls')),
                  path('', include('users.urls')),
                  path('news/', include('news.urls')),
                  path('summernote/', include('django_summernote.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

island/urls.py
from django.urls import path
from .views import home

app_name = 'island'
urlpatterns = [
    path('', home, name='home'),
]

news/urls.py
from django.urls import path
from .views import (NewsListView, NewsDetailView, NewsCreateView, NewsUpdateView, NewsDeleteView,
                    UserPostListView, TagListView, tag_detail)

app_name = 'news'
urlpatterns = [
    path('', NewsListView.as_view(), name='news'),
    path('author/<str:username>/', UserPostListView.as_view(), name='user-posts'),
    path('new/', NewsCreateView.as_view(), name='news-create'),
    path('tags/', TagListView.as_view(), name='tags'),
    path('tags/<slug:slug>/', tag_detail, name='tag-detail'),
    path('<slug:slug>/', NewsDetailView.as_view(), name='post'),
    path('<slug:slug>/update/', NewsUpdateView.as_view(), name='news-update'),
    path('<slug:slug>/delete/', NewsDeleteView.as_view(), name='news-delete'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}
        | Marooned
    {% endblock %}</title>

    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
    <meta name="google" content="notranslate"/>

</head>

<body>
<div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand ml-5" href="{% url 'island:home' %}">Marooned</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'island:home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'news:news' %}">News</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'news:tags' %}">Tags</a>
                </li>
            </ul>
        </div>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link text-primary" href="{% url 'news:news-create' %}">New Post</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'profile' %}">
                            <button class="btn btn-sm btn-outline-warning text-sm-center"
                                    type="submit">{{ user.username }}</button>
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'signout' %}">
                            <button class="btn btn-sm btn-outline-danger text-sm-center" type="submit">Sign Out</button>
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'signin' %}">
                            <button class="btn btn-sm btn-outline-primary text-sm-center" type="submit">Sign In</button>
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'signup' %}">
                            <button class="btn btn-sm btn-outline-success text-sm-center" type="submit">Get Started
                            </button>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {#Alert Message#}
    <div class="container col-md-8">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}"> {{ message }} </div>
            {% endfor %}
        {% endif %}
    </div>
    {% block body %}
    {% endblock %}

    <hr>
    <footer class="py-3 bg-grey">
        <p class="m-0 text-dark text-center ">Copyright &copy; Gazi Ashiq</p>
    </footer>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="{% static 'js/jquery-3.5.1.slim.min.js' %}"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"
        crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.min.js' %}"
        crossorigin="anonymous"></script>
</body>
</html>